services:
  # Service principal (Backend API uniquement)
  - type: web
    name: linkedin-prospector-api
    env: docker
    plan: starter
    region: oregon
    healthCheckPath: /health
    # Render cherche automatiquement ./Dockerfile par défaut
    # Nous devons donc renommer Dockerfile.render vers Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CLAUDE_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: UNIPILE_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true

databases:
  # Base de données PostgreSQL
  - name: linkedin-prospector-db
    databaseName: linkedin_prospector
    user: linkedin_prospector_user
    plan: starter
    region: oregon

  # Redis pour les queues
  - name: linkedin-prospector-redis
    databaseName: linkedin_prospector_redis
    plan: starter
    region: oregon
    maxmemoryPolicy: allkeys-lru 